<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="revampTestCase.SS_CheckOut_Public_Verify_GiftCard_Functionality" tests="1" time="115.187" ignored="0" failures="0" timestamp="28 Jul 2020 04:01:48 GMT" skipped="0" hostname="TO-NXGHGAA00163000A457600-L" errors="1">
  <testcase name="main" time="115.187" classname="revampTestCase.SS_CheckOut_Public_Verify_GiftCard_Functionality">
    <error type="java.io.IOException" message="Destination &#039;C:\Users\amithpDownloads\DesktopRegressionSuite\DesktopRegressionSuite\Screens\Test Results\Run_28_07_2020_05_53_30\Fail\SS_CheckOut_Public_Verify_GiftCard_Functionality_Failure.jpg&#039; directory cannot be created">
      <![CDATA[java.io.IOException: Destination 'C:\Users\amithpDownloads\DesktopRegressionSuite\DesktopRegressionSuite\Screens\Test Results\Run_28_07_2020_05_53_30\Fail\SS_CheckOut_Public_Verify_GiftCard_Functionality_Failure.jpg' directory cannot be created
	at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:646)
	at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:606)
	at utility.Utils.captureScreenshot(Utils.java:943)
	at revampTestCase.SS_CheckOut_Public_Verify_GiftCard_Functionality.main(SS_CheckOut_Public_Verify_GiftCard_Functionality.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- main -->
</testsuite> <!-- revampTestCase.SS_CheckOut_Public_Verify_GiftCard_Functionality -->
